### ISSUE TITLE
Firebase error testing the problem

### ISSUE THREAD

**Issue by diegomesata** [gabriel-hahn/whatsapp-clone-javascript#1]
Hello, I paste the firebase config like this:

 this._config = {
            apiKey: "A**",
            authDomain: "chat**",
            databaseURL: "https://chat**",
            projectId: "chat**",
            storageBucket: "chat**.appspot.com",
            messagingSenderId: "6**",
            appId: "1:6**"
          };

But after the user login, I got in the console:

@firebase/firestore: – "Firestore (5.5.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError

Could you help me? 

Thank you

**Comment by gabriel-hahn** [comment]
Hi @diegomesata , you can use the following settings just replacing 'Your API key' and 'Your project ID' for your Firebase configuration:

```
this._config = {
     apiKey: 'Your API key',
     authDomain: "Your project ID.firebaseapp.com",
     databaseURL: "https://Your project ID.firebaseio.com",
     projectId: 'Your project ID',
     storageBucket: "Your project ID.appspot.com",
};
```

It should work already, as I tested locally. After you set the correct configuration and run the project, a new tab will open to login with Gmail user.
